//! The cross-implementation contract: this harness replays the committed
//! safety-stock vectors — generated by the Python reference — against
//! the Rust implementation. Float comparisons are exact equality on the
//! 9-decimal-rounded values the vectors store; the algorithm is stated
//! step by step in both languages.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use tessera_inv::{Echelon, recommend};

const VECTORS: &str = include_str!("../../../reference/python/vectors/safety_stock.vectors.json");

fn ech(v: &serde_json::Value) -> Echelon {
    Echelon {
        name: v["name"].as_str().expect("name").to_string(),
        mean_demand: v["mean_demand"].as_f64().expect("mean_demand"),
        sd_demand: v["sd_demand"].as_f64().expect("sd_demand"),
        mean_lead_time: v["mean_lead_time"].as_f64().expect("mean_lead_time"),
        sd_lead_time: v["sd_lead_time"].as_f64().expect("sd_lead_time"),
        service_level: v["service_level"].as_f64().expect("service_level"),
        parent: v["parent"].as_u64().map(|p| p as usize),
    }
}

#[test]
fn rust_reproduces_every_safety_stock_vector() {
    let doc: serde_json::Value = serde_json::from_str(VECTORS).expect("valid vectors JSON");
    assert_eq!(doc["domain"], "safety-stock/1");
    assert_eq!(doc["method"], "staged-service-level-meio/1");
    let cases = doc["cases"].as_array().expect("cases array");
    assert!(!cases.is_empty(), "no vectors: the contract is empty");

    for case in cases {
        let name = case["name"].as_str().expect("case name");
        let echelons: Vec<Echelon> = case["echelons"]
            .as_array()
            .expect("echelons")
            .iter()
            .map(ech)
            .collect();
        let expected = &case["expected"];

        match recommend(&echelons) {
            Err(err) => {
                assert!(
                    !expected["ok"].as_bool().expect("expected.ok"),
                    "{name}: unexpected refusal: {err}"
                );
                assert_eq!(
                    err.to_string(),
                    expected["message"].as_str().expect("message"),
                    "{name}: refusal message is part of the contract"
                );
            }
            Ok(rec) => {
                assert!(
                    expected["ok"].as_bool().expect("expected.ok"),
                    "{name}: expected a refusal, got a recommendation"
                );
                assert_eq!(rec.method, expected["method"].as_str().expect("method"));
                let wanted = expected["echelons"].as_array().expect("echelons");
                assert_eq!(rec.echelons.len(), wanted.len(), "{name}");
                for (got, want) in rec.echelons.iter().zip(wanted) {
                    assert_eq!(got.name, want["name"].as_str().expect("name"), "{name}");
                    assert_eq!(
                        got.ss_units,
                        want["ss_units"].as_u64().expect("ss_units"),
                        "{name}/{}",
                        got.name
                    );
                    assert_eq!(
                        got.z,
                        want["z"].as_f64().expect("z"),
                        "{name}/{}: z must match to the stored 9 decimals",
                        got.name
                    );
                    assert_eq!(
                        got.sigma_dl,
                        want["sigma_dl"].as_f64().expect("sigma_dl"),
                        "{name}/{}: sigma_dl must match to the stored 9 decimals",
                        got.name
                    );
                    assert_eq!(
                        got.mean_demand,
                        want["mean_demand"].as_f64().expect("mean_demand"),
                        "{name}/{}",
                        got.name
                    );
                    assert_eq!(
                        got.sd_demand,
                        want["sd_demand"].as_f64().expect("sd_demand"),
                        "{name}/{}",
                        got.name
                    );
                }
                if let Some(explain) = expected["explain_0"].as_str() {
                    assert_eq!(rec.explain(0), explain, "{name}: the explainer is pinned");
                }
            }
        }
    }
}
