//! The cross-implementation contract: this harness replays the committed
//! access vectors — generated by the Python reference — against the Rust
//! engine. Both sides must produce the same code and layer for every case.
//! See docs/adr/0008 (vectors as the contract).

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::collections::BTreeSet;

use tessera_access::{
    Action, Actor, Decision, Effect, Env, Glob, Grant, Rule, RuleAction, Tier, evaluate,
};
use tessera_ids::{EpochMs, ModuleId, RoleId, SubjectId, TenantId};

const VECTORS: &str = include_str!("../../../reference/python/vectors/access.vectors.json");

fn mid(s: &str) -> ModuleId {
    ModuleId::new(s).expect("valid module id in vectors")
}

fn parse_env(v: &serde_json::Value) -> Env {
    let now = EpochMs::new(v["now"].as_u64().expect("env.now"));
    let mut env =
        Env::new(now).with_module_enabled(v["module_enabled"].as_bool().expect("module_enabled"));
    for c in v["known_columns"].as_array().expect("known_columns") {
        env = env.with_known_columns([c.as_str().expect("column")]);
    }
    for r in v["rules"].as_array().expect("rules") {
        env = env.with_rule(Rule {
            role: RoleId::new(r["role"].as_str().expect("role")).expect("valid role"),
            module: mid(r["module"].as_str().expect("module")),
            action: match r["action"].as_str().expect("action") {
                "read" => RuleAction::Read,
                "write" => RuleAction::Write,
                other => panic!("invalid rule action {other}"),
            },
            column: Glob::new(r["column"].as_str().expect("column")).expect("valid glob"),
            effect: match r["effect"].as_str().expect("effect") {
                "allow" => Effect::Allow,
                "deny" => Effect::Deny,
                other => panic!("invalid effect {other}"),
            },
        });
    }
    for g in v["grants"].as_array().expect("grants") {
        env = env.with_grant(Grant {
            owner: mid(g["owner"].as_str().expect("owner")),
            granted_to: mid(g["granted_to"].as_str().expect("granted_to")),
            columns: g["columns"]
                .as_array()
                .expect("columns")
                .iter()
                .map(|c| c.as_str().expect("column").to_string())
                .collect(),
            expires_at: g["expires_at"].as_u64().map(EpochMs::new),
        });
    }
    for pair in v["agent_allowlist"].as_array().expect("agent_allowlist") {
        let arr = pair.as_array().expect("pair");
        env = env.with_agent_allowlist(
            mid(arr[0].as_str().expect("module")),
            parse_action(arr[1].as_str().expect("action")),
        );
    }
    for triple in v["origin_approvals"].as_array().expect("origin_approvals") {
        let arr = triple.as_array().expect("triple");
        env = env.with_origin_approval(
            SubjectId::new(arr[0].as_str().expect("subject")).expect("valid subject"),
            mid(arr[1].as_str().expect("module")),
            parse_action(arr[2].as_str().expect("action")),
        );
    }
    env
}

fn parse_action(s: &str) -> Action {
    match s {
        "read" => Action::Read,
        "propose" => Action::Propose,
        "write" => Action::Write,
        other => panic!("invalid action {other}"),
    }
}

fn parse_request(v: &serde_json::Value) -> tessera_access::Request {
    let actor_v = &v["actor"];
    let actor = match actor_v["kind"].as_str().expect("actor.kind") {
        "user" => Actor::User {
            subject: SubjectId::new(actor_v["subject"].as_str().expect("subject"))
                .expect("valid subject"),
            role: RoleId::new(actor_v["role"].as_str().expect("role")).expect("valid role"),
        },
        "agent" => Actor::Agent {
            subject: SubjectId::new(actor_v["subject"].as_str().expect("subject"))
                .expect("valid subject"),
            tier: match actor_v["tier"].as_str().expect("tier") {
                "observe" => Tier::Observe,
                "advise" => Tier::Advise,
                "act" => Tier::Act,
                other => panic!("invalid tier {other}"),
            },
        },
        "origin" => Actor::Origin {
            subject: SubjectId::new(actor_v["subject"].as_str().expect("subject"))
                .expect("valid subject"),
        },
        other => panic!("invalid actor kind {other}"),
    };
    tessera_access::Request {
        tenant: TenantId::new("acme").expect("valid tenant"),
        actor,
        home: v["home"].as_str().map(mid),
        target: mid(v["target"].as_str().expect("target")),
        action: parse_action(v["action"].as_str().expect("action")),
        columns: v["columns"]
            .as_array()
            .map(|a| {
                a.iter()
                    .map(|c| c.as_str().expect("column").to_string())
                    .collect::<BTreeSet<String>>()
            })
            .unwrap_or_default(),
        origin_intent: v["origin_intent"]
            .as_str()
            .map(tessera_access::IntentRef::new)
            .transpose()
            .expect("valid intent ref"),
    }
}

#[test]
fn rust_reproduces_every_access_vector() {
    let doc: serde_json::Value = serde_json::from_str(VECTORS).expect("valid vectors JSON");
    assert_eq!(doc["domain"], "tessera-access/1");
    let cases = doc["cases"].as_array().expect("cases array");
    assert!(!cases.is_empty(), "no vectors: the contract is empty");

    // Every one of the fourteen codes must appear in the vector set.
    let codes: Vec<&str> = doc["codes"]
        .as_array()
        .expect("codes")
        .iter()
        .map(|c| c.as_str().expect("code"))
        .collect();
    assert_eq!(codes.len(), 14, "the contract pins exactly fourteen codes");

    let mut seen: BTreeSet<String> = BTreeSet::new();
    for case in cases {
        let name = case["name"].as_str().expect("case name");
        let env = parse_env(&case["env"]);
        let request = parse_request(&case["request"]);
        let Decision { code, layer } = evaluate(&request, &env);
        let expected_code = case["expected"]["code"].as_str().expect("code");
        let expected_layer = case["expected"]["layer"].as_str().expect("layer");
        assert_eq!(code.to_string(), expected_code, "{name}");
        assert_eq!(layer.to_string(), expected_layer, "{name}");
        seen.insert(expected_code.to_string());
    }
    for code in codes {
        assert!(
            seen.contains(code),
            "vector set claims to cover {code} but no case produces it"
        );
    }
}
