//! The cross-implementation contract: this harness replays the committed
//! ledger vectors — generated by the Python reference — against the Rust
//! implementation. Both sides must agree byte-for-byte on every prev, every
//! hash, and every first broken height. See docs/adr/0008 (vectors as the
//! contract) and docs/adr/0009 (the digest comes from an audited crate).

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use tessera_ids::TenantId;
use tessera_ledger::{Chain, Entry, verify};

const VECTORS: &str = include_str!("../../../reference/python/vectors/ledger.vectors.json");

fn hex_to_32(s: &str) -> [u8; 32] {
    let bytes = hex_decode(s);
    let mut out = [0u8; 32];
    out.copy_from_slice(&bytes);
    out
}

fn hex_decode(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("valid hex"))
        .collect()
}

fn flip(hex: &str, byte: usize) -> String {
    let mut raw = hex_decode(hex);
    let i = byte % raw.len();
    raw[i] ^= 0x01;
    raw.iter().map(|b| format!("{b:02x}")).collect()
}

#[test]
fn rust_reproduces_every_ledger_vector() {
    let doc: serde_json::Value = serde_json::from_str(VECTORS).expect("valid vectors JSON");
    assert_eq!(doc["domain"], "tessera-ledger/1");
    let cases = doc["cases"].as_array().expect("cases array");
    assert!(!cases.is_empty(), "no vectors: the contract is empty");

    for case in cases {
        let name = case["name"].as_str().expect("case name");
        let tenant =
            TenantId::new(case["tenant"].as_str().expect("tenant")).expect("valid tenant id");
        let entries: Vec<Entry> = case["entries"]
            .as_array()
            .expect("entries")
            .iter()
            .map(|e| Entry {
                height: e["height"].as_u64().expect("height"),
                valid_ms: e["valid_ms"].as_u64().expect("valid_ms"),
                system_ms: e["system_ms"].as_u64().expect("system_ms"),
                payload: hex_decode(e["payload_hex"].as_str().expect("payload_hex")),
            })
            .collect();

        // Build the chain the way the kernel would.
        let mut chain = Chain::new(tenant.clone());
        for e in &entries {
            chain
                .append(e.clone())
                .expect("vector entries append cleanly");
        }
        let mut records: Vec<tessera_ledger::Record> = chain.records().to_vec();

        // Apply the tamper exactly as the generator did. Payload tampers
        // modify the entry inside the record; hash/prev tampers modify the
        // committed linkage.
        if let Some(spec) = case["tamper"].as_object() {
            let index = spec["record"].as_u64().expect("record index") as usize;
            let byte = spec["byte"].as_u64().expect("byte") as usize;
            match spec["kind"].as_str().expect("kind") {
                "payload" => {
                    let payload = &mut records[index].entry.payload;
                    if payload.is_empty() {
                        payload.push(0x00);
                    } else {
                        let i = byte % payload.len();
                        payload[i] ^= 0x01;
                    }
                }
                "hash" => {
                    records[index].hash = hex_to_32(&flip(
                        &records[index]
                            .hash
                            .iter()
                            .map(|b| format!("{b:02x}"))
                            .collect::<String>(),
                        byte,
                    ));
                }
                "prev" => {
                    records[index].prev = hex_to_32(&flip(
                        &records[index]
                            .prev
                            .iter()
                            .map(|b| format!("{b:02x}"))
                            .collect::<String>(),
                        byte,
                    ));
                }
                other => panic!("unknown tamper kind: {other}"),
            }
        }

        // The committed hashes must match the vectors field for field.
        let expected = case["expected"]["records"]
            .as_array()
            .expect("expected records");
        assert_eq!(records.len(), expected.len(), "{name}: record count");
        for (got, want) in records.iter().zip(expected) {
            assert_eq!(
                got.prev
                    .iter()
                    .map(|b| format!("{b:02x}"))
                    .collect::<String>(),
                want["prev_hex"].as_str().expect("prev_hex"),
                "{name}: prev mismatch"
            );
            assert_eq!(
                got.hash
                    .iter()
                    .map(|b| format!("{b:02x}"))
                    .collect::<String>(),
                want["hash_hex"].as_str().expect("hash_hex"),
                "{name}: hash mismatch"
            );
        }

        // And verification must pin the same first broken height.
        let verdict = verify(&records);
        match case["expected"]["first_broken_height"].as_u64() {
            Some(height) => assert_eq!(verdict, Err(height), "{name}: first broken height"),
            None => assert_eq!(verdict, Ok(()), "{name}: chain should verify"),
        }
    }
}
